### ISSUE TITLE
Test basic to-do list functionalities 

### ISSUE THREAD

**Issue by drishya-nair** [chjy227743/cumulative.do#13]
- [ ] Test user's ability to manually input tasks.
- [ ] Test task check off when completed feature.
- [ ] Test task removal from list feature.
